cambios de login y registro
NelsonMilla/dev-dir pull request #2
Opened 2019-11-06 21:34 UTC by AntonioCardenas

Contenedores y estilos  incluyendo una funcion para cambiar vista mobile

2019-11-06 21:37 UTC, NelsonMilla commented on package-lock.json
> -    "material-design-icons": {
¿Porque estas sacando material icons de aquí? Quitalos porque creo que los estamos usando.

2019-11-06 21:37 UTC, NelsonMilla commented on package.json
> -    "material-design-icons": "^3.0.1",
Lo mismo de la vez pasada!

2019-11-06 21:41 UTC, NelsonMilla commented on src/index.html
> +  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.1/css/all.css">
Entonces cambiaste Material Icons por fontawesome? hiciste los cambios a todas las vistas tambien? ¡A la proxima hacelo en dos PRs separadas o agregalo a la descripción de la PR!

2019-11-06 21:41 UTC, NelsonMilla requested changes
Chequea los comentarios! @AntonioCardenas

2019-11-06 22:14 UTC, AntonioCardenas commented on src/index.html
> +  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.1/css/all.css">
En el siguiente commit se elimina y solo queda material icons del index.html

2019-11-06 22:14 UTC, AntonioCardenas commented on package.json
> -    "material-design-icons": "^3.0.1",
en la siguiente version desaparece

2019-11-06 22:14 UTC, AntonioCardenas commented on package-lock.json
> -    "material-design-icons": {
desaparece tambien del lock

2020-02-05 20:53 UTC, NelsonMilla commented
Cerrado por inactividad (?)

2020-02-05 20:53 UTC, closed without merging